from enum import Enum


class ProductFunctionality(str, Enum):
    """
    Список возможных продуктовых функциональностей в Allure TestOps
    """

    MESSAGING = "02. Messaging"
    CONTACTS = "03. Contacts"
    BASE_APP = "04. Base App"
    CALLS = "09. Calls"
    FEDERATIONS = "10. Federations"
    GROUP_POLICIES = "11. Group Policies"
    SEARCH = "12. Search"
    PROFILE = "13. Profile"
    ORGSTRUCTURE = "14. Orgstructure"
    MAIL = "16. Mail"
    CALENDAR = "17. Calendar"
    CLOUD = "18. Cloud"
    MINIAPPS = "19. MiniApps"
    BOT_API = "20. BotAPI"
    NOTIFICATIONS = "21. Notifications"
    SETTINGS = "22. Settings"
    AUTHENTICATION = "23. Authentication"
    SURVEYS = "24. Surveys"
    TASKS = "25. Tasks"
    DIGITAL_ASSISTANT = "26. Digital Assistant"
    CORE_DESIGN = "27. Core Design"
    DESIGN_SYSTEM = "28. Design System"
    CORE_BACKEND = "29. Core Backend"
    CORE_DEVOPS = "30. Core DevOps"
    CORE_WEB = "31. Core Web"
    CORE_DESKTOP = "32. Core Desktop"
    CORE_IOS = "33. Core iOS"
    CORE_ANDROID = "34. Core Android"
    CORE_QA = "35. Core QA"
    SUPPORT = "37. Support"
    RELEASE_AND_INFRA = "38. Release and Infrastructure"
    KUBERNETES = "39. Kubernetes"
    PLATFORM_INFRASTRUCTURE = "40. Platform Infrastructure"
    DEPLOYER_WORKSPACE = "41. Deployer (WorkSpace)"
    MAIL_WORKSPACE = "42. Mail (WorkSpace)"
    CALENDAR_WORKSPACE = "43. Calendar (WorkSpace)"
    ADMIN_PANEL_WORKSPACE = "44. Admin Panel (WorkSpace)"
    CLOUD_WORKSPACE = "45. Cloud (WorkSpace)"
    WORKMAIL_DESKTOP_WORKSPACE = "46. Workmail Desktop (WorkSpace)"
    RATES_AND_FUNNEL_WORKSPACE = "47. Rates and Funnel (WorkSpace)"
    BACK_OFFICE_WORKSPACE = "48. Back Office (Workspace)"
    SRE_CORE = "49. SRE Core"
    SRE_VKT = "50. SRE VKT"
    SRE_WS = "51. SRE WS"
    SRE_SKTI = "52. SRE СКЗИ"
