# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.test_case_search_controller_api import TestCaseSearchControllerApi  # noqa: E501


class TestTestCaseSearchControllerApi(unittest.TestCase):
    """TestCaseSearchControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TestCaseSearchControllerApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_search1(self) -> None:
        """Test case for search1

        Find all test cases by given AQL  # noqa: E501
        """
        pass

    def test_validate_query1(self) -> None:
        """Test case for validate_query1

        Find all test cases by given AQL  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
