# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.member_controller_api import MemberControllerApi  # noqa: E501


class TestMemberControllerApi(unittest.TestCase):
    """MemberControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MemberControllerApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create23(self) -> None:
        """Test case for create23

        Create a new role user  # noqa: E501
        """
        pass

    def test_delete23(self) -> None:
        """Test case for delete23

        Delete role user by id  # noqa: E501
        """
        pass

    def test_find_all25(self) -> None:
        """Test case for find_all25

        Find all role users  # noqa: E501
        """
        pass

    def test_find_one19(self) -> None:
        """Test case for find_one19

        Find role user by id  # noqa: E501
        """
        pass

    def test_patch21(self) -> None:
        """Test case for patch21

        Patch role user  # noqa: E501
        """
        pass

    def test_suggest10(self) -> None:
        """Test case for suggest10

        Suggest members  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
