# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.page_permission_set_dto import PagePermissionSetDto  # noqa: E501

class TestPagePermissionSetDto(unittest.TestCase):
    """PagePermissionSetDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PagePermissionSetDto:
        """Test PagePermissionSetDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PagePermissionSetDto`
        """
        model = PagePermissionSetDto()  # noqa: E501
        if include_optional:
            return PagePermissionSetDto(
                total_elements = 56,
                total_pages = 56,
                size = 56,
                content = [
                    openapi_client.models.permission_set_dto.PermissionSetDto(
                        id = 56, 
                        name = '', 
                        permissions = [
                            'project:configure'
                            ], )
                    ],
                number = 56,
                sort = openapi_client.models.sort_object.SortObject(
                    empty = True, 
                    sorted = True, 
                    unsorted = True, ),
                number_of_elements = 56,
                pageable = openapi_client.models.pageable.Pageable(
                    offset = 56, 
                    sort = openapi_client.models.sort_object.SortObject(
                        empty = True, 
                        sorted = True, 
                        unsorted = True, ), 
                    page_number = 56, 
                    page_size = 56, 
                    unpaged = True, 
                    paged = True, ),
                first = True,
                last = True,
                empty = True
            )
        else:
            return PagePermissionSetDto(
        )
        """

    def testPagePermissionSetDto(self):
        """Test PagePermissionSetDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
