# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.analytic_controller_api import AnalyticControllerApi  # noqa: E501


class TestAnalyticControllerApi(unittest.TestCase):
    """AnalyticControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnalyticControllerApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_automation_chart(self) -> None:
        """Test case for automation_chart

        """
        pass

    def test_group_by_automation(self) -> None:
        """Test case for group_by_automation

        """
        pass

    def test_group_by_status(self) -> None:
        """Test case for group_by_status

        """
        pass

    def test_last_results(self) -> None:
        """Test case for last_results

        """
        pass

    def test_launch_duration_histogram(self) -> None:
        """Test case for launch_duration_histogram

        """
        pass

    def test_mute_trend(self) -> None:
        """Test case for mute_trend

        """
        pass

    def test_statistic_trend(self) -> None:
        """Test case for statistic_trend

        """
        pass

    def test_success_rate(self) -> None:
        """Test case for success_rate

        """
        pass


if __name__ == '__main__':
    unittest.main()
