# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.workflow_schema_controller_api import WorkflowSchemaControllerApi  # noqa: E501


class TestWorkflowSchemaControllerApi(unittest.TestCase):
    """WorkflowSchemaControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkflowSchemaControllerApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create(self) -> None:
        """Test case for create

        Create a new workflow schema  # noqa: E501
        """
        pass

    def test_delete1(self) -> None:
        """Test case for delete1

        Delete workflow schema by given id  # noqa: E501
        """
        pass

    def test_find_all(self) -> None:
        """Test case for find_all

        Find all workflow schemas for given project  # noqa: E501
        """
        pass

    def test_find_one(self) -> None:
        """Test case for find_one

        Find workflow schema by given id  # noqa: E501
        """
        pass

    def test_patch(self) -> None:
        """Test case for patch

        Update workflow schema  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
