# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.role_controller_api import RoleControllerApi  # noqa: E501


class TestRoleControllerApi(unittest.TestCase):
    """RoleControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RoleControllerApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create18(self) -> None:
        """Test case for create18

        Create a new role  # noqa: E501
        """
        pass

    def test_delete18(self) -> None:
        """Test case for delete18

        Delete role by id  # noqa: E501
        """
        pass

    def test_find_all17(self) -> None:
        """Test case for find_all17

        Find all roles  # noqa: E501
        """
        pass

    def test_find_one15(self) -> None:
        """Test case for find_one15

        Find role by id  # noqa: E501
        """
        pass

    def test_patch17(self) -> None:
        """Test case for patch17

        Patch a role  # noqa: E501
        """
        pass

    def test_suggest8(self) -> None:
        """Test case for suggest8

        Suggest roles  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
