# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.test_case_csv_import_controller_api import TestCaseCsvImportControllerApi  # noqa: E501


class TestTestCaseCsvImportControllerApi(unittest.TestCase):
    """TestCaseCsvImportControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TestCaseCsvImportControllerApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_info(self) -> None:
        """Test case for info

        Get testcase csv import file and return import info  # noqa: E501
        """
        pass

    def test_preview(self) -> None:
        """Test case for preview

        Preview testcase csv import  # noqa: E501
        """
        pass

    def test_submit(self) -> None:
        """Test case for submit

        Submit testcase csv import  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
