# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.launch_member_stats_dto import LaunchMemberStatsDto  # noqa: E501

class TestLaunchMemberStatsDto(unittest.TestCase):
    """LaunchMemberStatsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LaunchMemberStatsDto:
        """Test LaunchMemberStatsDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LaunchMemberStatsDto`
        """
        model = LaunchMemberStatsDto()  # noqa: E501
        if include_optional:
            return LaunchMemberStatsDto(
                assignee = '',
                statistic = [
                    openapi_client.models.test_status_count.TestStatusCount(
                        status = 'failed', 
                        count = 56, )
                    ],
                muted_count = 56,
                retried_count = 56,
                defects_count = 56,
                duration_sum = 56
            )
        else:
            return LaunchMemberStatsDto(
        )
        """

    def testLaunchMemberStatsDto(self):
        """Test LaunchMemberStatsDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
