# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.job_controller_api import JobControllerApi  # noqa: E501


class TestJobControllerApi(unittest.TestCase):
    """JobControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JobControllerApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create27(self) -> None:
        """Test case for create27

        Create a new job  # noqa: E501
        """
        pass

    def test_delete26(self) -> None:
        """Test case for delete26

        Delete job by id  # noqa: E501
        """
        pass

    def test_find_all271(self) -> None:
        """Test case for find_all271

        Find job by given project and external id  # noqa: E501
        """
        pass

    def test_find_one22(self) -> None:
        """Test case for find_one22

        Find job by id  # noqa: E501
        """
        pass

    def test_get_candidate(self) -> None:
        """Test case for get_candidate

        Get suggest for job candidate  # noqa: E501
        """
        pass

    def test_get_groups2(self) -> None:
        """Test case for get_groups2

        Find tree groups for node  # noqa: E501
        """
        pass

    def test_get_leaves(self) -> None:
        """Test case for get_leaves

        Find tree leaves for node  # noqa: E501
        """
        pass

    def test_get_suggest1(self) -> None:
        """Test case for get_suggest1

        Suggest for jobs  # noqa: E501
        """
        pass

    def test_patch24(self) -> None:
        """Test case for patch24

        Patch job  # noqa: E501
        """
        pass

    def test_run4(self) -> None:
        """Test case for run4

        Run job to a new launch  # noqa: E501
        """
        pass

    def test_sync2(self) -> None:
        """Test case for sync2

        Sync job with build server  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
