# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.env_var_controller_api import EnvVarControllerApi  # noqa: E501


class TestEnvVarControllerApi(unittest.TestCase):
    """EnvVarControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EnvVarControllerApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create36(self) -> None:
        """Test case for create36

        Create a new environment variable  # noqa: E501
        """
        pass

    def test_create37(self) -> None:
        """Test case for create37

        Create a new environment variable  # noqa: E501
        """
        pass

    def test_delete34(self) -> None:
        """Test case for delete34

        Delete environment variable by id  # noqa: E501
        """
        pass

    def test_delete35(self) -> None:
        """Test case for delete35

        Delete environment variable by id  # noqa: E501
        """
        pass

    def test_find_all36(self) -> None:
        """Test case for find_all36

        Find all environment variables  # noqa: E501
        """
        pass

    def test_find_all37(self) -> None:
        """Test case for find_all37

        Find all environment variables  # noqa: E501
        """
        pass

    def test_find_one30(self) -> None:
        """Test case for find_one30

        Find environment variable by id  # noqa: E501
        """
        pass

    def test_find_one31(self) -> None:
        """Test case for find_one31

        Find environment variable by id  # noqa: E501
        """
        pass

    def test_merge1(self) -> None:
        """Test case for merge1

        Merge environment variables  # noqa: E501
        """
        pass

    def test_merge2(self) -> None:
        """Test case for merge2

        Merge environment variables  # noqa: E501
        """
        pass

    def test_patch33(self) -> None:
        """Test case for patch33

        Patch environment variable  # noqa: E501
        """
        pass

    def test_patch34(self) -> None:
        """Test case for patch34

        Patch environment variable  # noqa: E501
        """
        pass

    def test_suggest17(self) -> None:
        """Test case for suggest17

        Suggest environment variables  # noqa: E501
        """
        pass

    def test_suggest18(self) -> None:
        """Test case for suggest18

        Suggest environment variables  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
