# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.integration_operation_type_dto import IntegrationOperationTypeDto  # noqa: E501

class TestIntegrationOperationTypeDto(unittest.TestCase):
    """IntegrationOperationTypeDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIntegrationOperationTypeDto(self):
        """Test IntegrationOperationTypeDto"""
        # inst = IntegrationOperationTypeDto()

if __name__ == '__main__':
    unittest.main()
