# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.test_case_sync_controller_api import TestCaseSyncControllerApi  # noqa: E501


class TestTestCaseSyncControllerApi(unittest.TestCase):
    """TestCaseSyncControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TestCaseSyncControllerApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_sync1(self) -> None:
        """Test case for sync1

        Clone test case  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
