# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.comment_controller_api import CommentControllerApi  # noqa: E501


class TestCommentControllerApi(unittest.TestCase):
    """CommentControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommentControllerApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create41(self) -> None:
        """Test case for create41

        Create a new comment  # noqa: E501
        """
        pass

    def test_delete39(self) -> None:
        """Test case for delete39

        Delete comment by id  # noqa: E501
        """
        pass

    def test_find_all38(self) -> None:
        """Test case for find_all38

        Find all comments  # noqa: E501
        """
        pass

    def test_find_one33(self) -> None:
        """Test case for find_one33

        Find comment by id  # noqa: E501
        """
        pass

    def test_patch38(self) -> None:
        """Test case for patch38

        Dynamic update comment  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
