# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.project_group_access_dto import ProjectGroupAccessDto  # noqa: E501

class TestProjectGroupAccessDto(unittest.TestCase):
    """ProjectGroupAccessDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectGroupAccessDto:
        """Test ProjectGroupAccessDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectGroupAccessDto`
        """
        model = ProjectGroupAccessDto()  # noqa: E501
        if include_optional:
            return ProjectGroupAccessDto(
                group = openapi_client.models.access_group_dto.AccessGroupDto(
                    id = 56, 
                    name = '', 
                    users = [
                        openapi_client.models.access_group_user_dto.AccessGroupUserDto(
                            username = '', )
                        ], 
                    users_count = 56, 
                    projects_count = 56, ),
                permission_set_id = 56,
                permission_set_name = ''
            )
        else:
            return ProjectGroupAccessDto(
                group = openapi_client.models.access_group_dto.AccessGroupDto(
                    id = 56, 
                    name = '', 
                    users = [
                        openapi_client.models.access_group_user_dto.AccessGroupUserDto(
                            username = '', )
                        ], 
                    users_count = 56, 
                    projects_count = 56, ),
                permission_set_id = 56,
        )
        """

    def testProjectGroupAccessDto(self):
        """Test ProjectGroupAccessDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
