# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.page_launch_preview_dto import PageLaunchPreviewDto  # noqa: E501

class TestPageLaunchPreviewDto(unittest.TestCase):
    """PageLaunchPreviewDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageLaunchPreviewDto:
        """Test PageLaunchPreviewDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageLaunchPreviewDto`
        """
        model = PageLaunchPreviewDto()  # noqa: E501
        if include_optional:
            return PageLaunchPreviewDto(
                total_elements = 56,
                total_pages = 56,
                size = 56,
                content = [
                    openapi_client.models.launch_preview_dto.LaunchPreviewDto(
                        id = 56, 
                        name = '', 
                        project_id = 56, 
                        statistic = [
                            openapi_client.models.test_status_count.TestStatusCount(
                                status = 'failed', 
                                count = 56, )
                            ], 
                        tags = [
                            openapi_client.models.launch_tag_dto.LaunchTagDto(
                                id = 56, 
                                name = '', )
                            ], 
                        issues = [
                            openapi_client.models.issue_dto.IssueDto(
                                id = 56, 
                                integration_id = 56, 
                                name = '', 
                                url = '', 
                                summary = '', 
                                closed = True, )
                            ], 
                        links = [
                            openapi_client.models.external_link_dto.ExternalLinkDto(
                                name = '', 
                                url = '', 
                                type = '', )
                            ], 
                        environment = [
                            openapi_client.models.env_var_value_dto.EnvVarValueDto(
                                id = 56, 
                                name = '', 
                                variable = openapi_client.models.env_var_dto.EnvVarDto(
                                    id = 56, 
                                    name = '', 
                                    created_date = 56, 
                                    last_modified_date = 56, 
                                    created_by = '', 
                                    last_modified_by = '', ), )
                            ], 
                        jobs = [
                            openapi_client.models.job_run_dto.JobRunDto(
                                id = 56, 
                                name = '', 
                                url = '', 
                                external_id = '', 
                                stage = 'run_failure', 
                                error_message = '', 
                                job = openapi_client.models.job_info_dto.JobInfoDto(
                                    id = 56, 
                                    name = '', 
                                    url = '', 
                                    type = 'allure_testops', ), 
                                launch_id = 56, 
                                created_date = 56, 
                                last_modified_date = 56, 
                                created_by = '', 
                                last_modified_by = '', )
                            ], 
                        closed = True, 
                        external = True, 
                        new_defects_count = 56, 
                        known_defects_count = 56, 
                        created_date = 56, 
                        last_modified_date = 56, 
                        created_by = '', 
                        last_modified_by = '', )
                    ],
                number = 56,
                sort = openapi_client.models.sort_object.SortObject(
                    empty = True, 
                    sorted = True, 
                    unsorted = True, ),
                number_of_elements = 56,
                pageable = openapi_client.models.pageable.Pageable(
                    offset = 56, 
                    sort = openapi_client.models.sort_object.SortObject(
                        empty = True, 
                        sorted = True, 
                        unsorted = True, ), 
                    page_number = 56, 
                    page_size = 56, 
                    unpaged = True, 
                    paged = True, ),
                first = True,
                last = True,
                empty = True
            )
        else:
            return PageLaunchPreviewDto(
        )
        """

    def testPageLaunchPreviewDto(self):
        """Test PageLaunchPreviewDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
