# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.page_category_matcher_dto import PageCategoryMatcherDto  # noqa: E501

class TestPageCategoryMatcherDto(unittest.TestCase):
    """PageCategoryMatcherDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageCategoryMatcherDto:
        """Test PageCategoryMatcherDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageCategoryMatcherDto`
        """
        model = PageCategoryMatcherDto()  # noqa: E501
        if include_optional:
            return PageCategoryMatcherDto(
                total_elements = 56,
                total_pages = 56,
                size = 56,
                content = [
                    openapi_client.models.category_matcher_dto.CategoryMatcherDto(
                        id = 56, 
                        project_id = 56, 
                        name = '', 
                        category = openapi_client.models.category_dto.CategoryDto(
                            id = 56, 
                            project_id = 56, 
                            name = '', 
                            color = '', 
                            description = '', 
                            created_date = 56, 
                            last_modified_date = 56, 
                            created_by = '', 
                            last_modified_by = '', ), 
                        message_regex = '', 
                        trace_regex = '', 
                        created_date = 56, 
                        last_modified_date = 56, 
                        created_by = '', 
                        last_modified_by = '', )
                    ],
                number = 56,
                sort = openapi_client.models.sort_object.SortObject(
                    empty = True, 
                    sorted = True, 
                    unsorted = True, ),
                number_of_elements = 56,
                pageable = openapi_client.models.pageable.Pageable(
                    offset = 56, 
                    sort = openapi_client.models.sort_object.SortObject(
                        empty = True, 
                        sorted = True, 
                        unsorted = True, ), 
                    page_number = 56, 
                    page_size = 56, 
                    unpaged = True, 
                    paged = True, ),
                first = True,
                last = True,
                empty = True
            )
        else:
            return PageCategoryMatcherDto(
        )
        """

    def testPageCategoryMatcherDto(self):
        """Test PageCategoryMatcherDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
