# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.test_case_bulk_layer_dto import TestCaseBulkLayerDto  # noqa: E501

class TestTestCaseBulkLayerDto(unittest.TestCase):
    """TestCaseBulkLayerDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestCaseBulkLayerDto:
        """Test TestCaseBulkLayerDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestCaseBulkLayerDto`
        """
        model = TestCaseBulkLayerDto()  # noqa: E501
        if include_optional:
            return TestCaseBulkLayerDto(
                selection = openapi_client.models.test_case_tree_selection_dto.TestCaseTreeSelectionDto(
                    inverted = True, 
                    groups_include = [
                        [
                            56
                            ]
                        ], 
                    groups_exclude = [
                        [
                            56
                            ]
                        ], 
                    leafs_include = [
                        56
                        ], 
                    leafs_exclude = [
                        56
                        ], 
                    path = [
                        56
                        ], 
                    project_id = 56, 
                    tree_id = 56, 
                    filter_id = 56, 
                    search = '', ),
                layer_id = 56
            )
        else:
            return TestCaseBulkLayerDto(
                selection = openapi_client.models.test_case_tree_selection_dto.TestCaseTreeSelectionDto(
                    inverted = True, 
                    groups_include = [
                        [
                            56
                            ]
                        ], 
                    groups_exclude = [
                        [
                            56
                            ]
                        ], 
                    leafs_include = [
                        56
                        ], 
                    leafs_exclude = [
                        56
                        ], 
                    path = [
                        56
                        ], 
                    project_id = 56, 
                    tree_id = 56, 
                    filter_id = 56, 
                    search = '', ),
        )
        """

    def testTestCaseBulkLayerDto(self):
        """Test TestCaseBulkLayerDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
