# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.test_tag_controller_api import TestTagControllerApi  # noqa: E501


class TestTestTagControllerApi(unittest.TestCase):
    """TestTagControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TestTagControllerApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create15(self) -> None:
        """Test case for create15

        Create a new test tag  # noqa: E501
        """
        pass

    def test_delete15(self) -> None:
        """Test case for delete15

        Delete test tag by id  # noqa: E501
        """
        pass

    def test_find_all14(self) -> None:
        """Test case for find_all14

        Find all test tags  # noqa: E501
        """
        pass

    def test_find_one12(self) -> None:
        """Test case for find_one12

        Find test tag by id  # noqa: E501
        """
        pass

    def test_patch14(self) -> None:
        """Test case for patch14

        Patch test tag  # noqa: E501
        """
        pass

    def test_suggest6(self) -> None:
        """Test case for suggest6

        Suggest test tags  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
