# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.widget_options_tc_tree_map import WidgetOptionsTcTreeMap  # noqa: E501

class TestWidgetOptionsTcTreeMap(unittest.TestCase):
    """WidgetOptionsTcTreeMap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WidgetOptionsTcTreeMap:
        """Test WidgetOptionsTcTreeMap
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WidgetOptionsTcTreeMap`
        """
        model = WidgetOptionsTcTreeMap()  # noqa: E501
        if include_optional:
            return WidgetOptionsTcTreeMap(
                tc_rql = '',
                tree_id = 56
            )
        else:
            return WidgetOptionsTcTreeMap(
                tree_id = 56,
        )
        """

    def testWidgetOptionsTcTreeMap(self):
        """Test WidgetOptionsTcTreeMap"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
