# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.test_plan_dto import TestPlanDto  # noqa: E501

class TestTestPlanDto(unittest.TestCase):
    """TestPlanDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TestPlanDto:
        """Test TestPlanDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TestPlanDto`
        """
        model = TestPlanDto()  # noqa: E501
        if include_optional:
            return TestPlanDto(
                id = 56,
                project_id = 56,
                name = '',
                base_rql = '',
                tree = openapi_client.models.id_and_name_only_dto.IdAndNameOnlyDto(
                    id = 56, 
                    name = '', ),
                tree_selection = openapi_client.models.tree_selection_dto.TreeSelectionDto(
                    inverted = True, 
                    groups_include = [
                        [
                            56
                            ]
                        ], 
                    groups_exclude = [
                        [
                            56
                            ]
                        ], 
                    leafs_include = [
                        56
                        ], 
                    leafs_exclude = [
                        56
                        ], 
                    path = [
                        56
                        ], ),
                test_cases_count = 56,
                created_date = 56,
                last_modified_date = 56,
                created_by = '',
                last_modified_by = ''
            )
        else:
            return TestPlanDto(
        )
        """

    def testTestPlanDto(self):
        """Test TestPlanDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
