# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.project_access_controller_api import ProjectAccessControllerApi  # noqa: E501


class TestProjectAccessControllerApi(unittest.TestCase):
    """ProjectAccessControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectAccessControllerApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_add_project_collaborators(self) -> None:
        """Test case for add_project_collaborators

        Add collaborators to project  # noqa: E501
        """
        pass

    def test_add_project_groups(self) -> None:
        """Test case for add_project_groups

        Add groups to project  # noqa: E501
        """
        pass

    def test_delete_project_groups(self) -> None:
        """Test case for delete_project_groups

        Delete groups from project  # noqa: E501
        """
        pass

    def test_delete_users(self) -> None:
        """Test case for delete_users

        Delete collaborators from project  # noqa: E501
        """
        pass

    def test_get_project_access_groups(self) -> None:
        """Test case for get_project_access_groups

        Get project access groups  # noqa: E501
        """
        pass

    def test_get_project_collaborators(self) -> None:
        """Test case for get_project_collaborators

        Get project collaborators  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
