# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.export_controller_api import ExportControllerApi  # noqa: E501


class TestExportControllerApi(unittest.TestCase):
    """ExportControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExportControllerApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_generate1(self) -> None:
        """Test case for generate1

        Generate launch pdf report  # noqa: E501
        """
        pass

    def test_generate_test_case_csv_export(self) -> None:
        """Test case for generate_test_case_csv_export

        Generate test cases csv report  # noqa: E501
        """
        pass

    def test_generate_test_case_pdf_export(self) -> None:
        """Test case for generate_test_case_pdf_export

        Generate test cases pdf report  # noqa: E501
        """
        pass

    def test_generate_test_result_csv_export(self) -> None:
        """Test case for generate_test_result_csv_export

        Generate test results csv report  # noqa: E501
        """
        pass

    def test_get_supported_launch_pdf_content(self) -> None:
        """Test case for get_supported_launch_pdf_content

        Get supported launch pdf report parts  # noqa: E501
        """
        pass

    def test_get_supported_tc_fields(self) -> None:
        """Test case for get_supported_tc_fields

        Get supported test case export fields  # noqa: E501
        """
        pass

    def test_get_supported_tr_fields(self) -> None:
        """Test case for get_supported_tr_fields

        Get supported test result export fields  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
