# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.category_matcher_controller_api import CategoryMatcherControllerApi  # noqa: E501


class TestCategoryMatcherControllerApi(unittest.TestCase):
    """CategoryMatcherControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CategoryMatcherControllerApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create46(self) -> None:
        """Test case for create46

        """
        pass

    def test_delete_by_id4(self) -> None:
        """Test case for delete_by_id4

        """
        pass

    def test_find_all422(self) -> None:
        """Test case for find_all422

        """
        pass

    def test_patch43(self) -> None:
        """Test case for patch43

        """
        pass


if __name__ == '__main__':
    unittest.main()
