# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.status_dto import StatusDto  # noqa: E501

class TestStatusDto(unittest.TestCase):
    """StatusDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatusDto:
        """Test StatusDto
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatusDto`
        """
        model = StatusDto()  # noqa: E501
        if include_optional:
            return StatusDto(
                id = 56,
                name = '',
                color = '',
                created_date = 56,
                last_modified_date = 56,
                created_by = '',
                last_modified_by = ''
            )
        else:
            return StatusDto(
        )
        """

    def testStatusDto(self):
        """Test StatusDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
