[tool.poetry]
name = "allure-defect-matcher"
version = "0.1.0"
description = ""
authors = ["Валерий Коробов <v.korobov@corp.mail.ru>"]
readme = "README.md"
packages = [{include = "allure_defect_matcher"}]

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

