{
 "title": "IM QA Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Project",
    "label": "Project",
    "query": "IMDESKTOP,IMIOS,IMA,IMWEB,IMSERVER"
   },
   { "name": "Days", "query": "7,30,90" },
   { "name": "Hours", "label": "Hours", "query": "business,calendar" },
   {
    "name": "Status",
    "label": "Status",
    "query": "Ready for test,Testing,Тестирование"
   },
   {
    "name": "Priority",
    "label": "Priority",
    "query": "Стандартный,Критический,Блокирующий"
   },
   { "name": "Percentile", "label": "Percentile", "query": "p50,p80,p95" }
  ]
 },
 "panels": [
  {
   "title": "Tasks count | $Project",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "project_tasks_status{project=~\"$Project\", status=\"Ready for test\", days=\"$Days\", priority=~\"$Priority\"}",
     "legendFormat": "{{ project }} | {{status}} | {{priority}}"
    },
    {
     "expr": "sum(project_tasks_status{project=~\"$Project\", status=~\"$Status\", days=\"$Days\", priority=~\"$Priority\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "project_tasks_status{project=~\"$Project\", status=\"Тестирование\", days=\"$Days\", priority=~\"$Priority\"}",
     "legendFormat": "{{ project }} | {{status}} | {{priority}}"
    }
   ]
  },
  {
   "title": "$Project | $Hours | $Priority | $Status | Avg period in hours",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "stats_hours_avg{project=~\"$Project\", days=\"$Days\", status=~\"$Status\", priority=~\"$Priority\", hours_type=\"$Hours\"}",
     "legendFormat": "{{ project }} | {{ status }} | {{ priority }}, hrs"
    },
    {
     "expr": "sum(stats_hours_avg{project=~\"$Project\", days=\"$Days\", priority=~\"$Priority\", hours_type=\"$Hours\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$Project | $Hours | $Priority | $Status | $Percentile | Percentile hours",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "stats_hours_percentile_by_status{project=~\"$Project\", priority=~\"$Priority\", status=~\"$Status\", days=\"$Days\", hours_type=\"$Hours\", percent=\"$Percentile\"}",
     "legendFormat": "{{ project }} | {{ priority }} | {{ status }}"
    },
    {
     "expr": "sum(stats_hours_percentile_by_status{project=~\"$Project\", priority=~\"$Priority\", status=~\"$Status\", days=\"$Days\", hours_type=\"$Hours\", percent=\"$Percentile\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$Project | $Priority | Ready for test | Hours avg by assignee",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "stats_hours_avg_count_by_author{project=~\"$Project\", priority=~\"$Priority\", status=\"Ready for test\", days=\"$Days\", hours_type=\"$Hours\"}",
     "legendFormat": "{{ project }} | {{ priority }} | {{ author }}"
    }
   ]
  },
  {
   "title": "$Project | $Priority | Testing | Hours avg by assignee",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "stats_hours_avg_count_by_author{project=~\"$Project\", priority=~\"$Priority\", status=\"Testing\", days=\"$Days\", hours_type=\"$Hours\"}",
     "legendFormat": "{{ project }} | {{ priority }} | {{ author }}"
    }
   ]
  },
  {
   "title": "$Project | $Priority | Task return count",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "stats_task_return_count{project=~\"$Project\", priority=~\"$Priority\", days=\"$Days\"}",
     "legendFormat": "{{ project }} | {{ priority }} | {{ task }}"
    }
   ]
  }
 ]
}