# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from openapi_client.models.category_dto import CategoryDto

class CategoryMatcherDto(BaseModel):
    """
      # noqa: E501
    """
    id: Optional[StrictInt] = None
    project_id: Optional[StrictInt] = Field(default=None, alias="projectId")
    name: Optional[StrictStr] = None
    category: Optional[CategoryDto] = None
    message_regex: Optional[StrictStr] = Field(default=None, alias="messageRegex")
    trace_regex: Optional[StrictStr] = Field(default=None, alias="traceRegex")
    created_date: Optional[StrictInt] = Field(default=None, alias="createdDate")
    last_modified_date: Optional[StrictInt] = Field(default=None, alias="lastModifiedDate")
    created_by: Optional[StrictStr] = Field(default=None, alias="createdBy")
    last_modified_by: Optional[StrictStr] = Field(default=None, alias="lastModifiedBy")
    __properties = ["id", "projectId", "name", "category", "messageRegex", "traceRegex", "createdDate", "lastModifiedDate", "createdBy", "lastModifiedBy"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CategoryMatcherDto:
        """Create an instance of CategoryMatcherDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of category
        if self.category:
            _dict['category'] = self.category.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CategoryMatcherDto:
        """Create an instance of CategoryMatcherDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CategoryMatcherDto.parse_obj(obj)

        _obj = CategoryMatcherDto.parse_obj({
            "id": obj.get("id"),
            "project_id": obj.get("projectId"),
            "name": obj.get("name"),
            "category": CategoryDto.from_dict(obj.get("category")) if obj.get("category") is not None else None,
            "message_regex": obj.get("messageRegex"),
            "trace_regex": obj.get("traceRegex"),
            "created_date": obj.get("createdDate"),
            "last_modified_date": obj.get("lastModifiedDate"),
            "created_by": obj.get("createdBy"),
            "last_modified_by": obj.get("lastModifiedBy")
        })
        return _obj


