# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class CsvImportOptions(BaseModel):
    """
      # noqa: E501
    """
    with_headers: Optional[StrictBool] = Field(default=None, alias="withHeaders")
    auto_detect_format: Optional[StrictBool] = Field(default=None, alias="autoDetectFormat")
    column_separator: Optional[StrictStr] = Field(default=None, alias="columnSeparator")
    escape_char: Optional[StrictStr] = Field(default=None, alias="escapeChar")
    quote_char: Optional[StrictStr] = Field(default=None, alias="quoteChar")
    __properties = ["withHeaders", "autoDetectFormat", "columnSeparator", "escapeChar", "quoteChar"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CsvImportOptions:
        """Create an instance of CsvImportOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CsvImportOptions:
        """Create an instance of CsvImportOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CsvImportOptions.parse_obj(obj)

        _obj = CsvImportOptions.parse_obj({
            "with_headers": obj.get("withHeaders"),
            "auto_detect_format": obj.get("autoDetectFormat"),
            "column_separator": obj.get("columnSeparator"),
            "escape_char": obj.get("escapeChar"),
            "quote_char": obj.get("quoteChar")
        })
        return _obj


