# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt, constr

class CustomFieldSchemaCreateDto(BaseModel):
    """
      # noqa: E501
    """
    project_id: StrictInt = Field(default=..., alias="projectId")
    key: constr(strict=True, max_length=255, min_length=1) = Field(...)
    custom_field_id: StrictInt = Field(default=..., alias="customFieldId")
    __properties = ["projectId", "key", "customFieldId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CustomFieldSchemaCreateDto:
        """Create an instance of CustomFieldSchemaCreateDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CustomFieldSchemaCreateDto:
        """Create an instance of CustomFieldSchemaCreateDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CustomFieldSchemaCreateDto.parse_obj(obj)

        _obj = CustomFieldSchemaCreateDto.parse_obj({
            "project_id": obj.get("projectId"),
            "key": obj.get("key"),
            "custom_field_id": obj.get("customFieldId")
        })
        return _obj


