# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictInt
from openapi_client.models.list_selection_dto import ListSelectionDto

class DefectBulkDto(BaseModel):
    """
      # noqa: E501
    """
    project_id: StrictInt = Field(default=..., alias="projectId")
    selection: ListSelectionDto = Field(...)
    __properties = ["projectId", "selection"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DefectBulkDto:
        """Create an instance of DefectBulkDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of selection
        if self.selection:
            _dict['selection'] = self.selection.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DefectBulkDto:
        """Create an instance of DefectBulkDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DefectBulkDto.parse_obj(obj)

        _obj = DefectBulkDto.parse_obj({
            "project_id": obj.get("projectId"),
            "selection": ListSelectionDto.from_dict(obj.get("selection")) if obj.get("selection") is not None else None
        })
        return _obj


