# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from openapi_client.models.test_case_create_dto import TestCaseCreateDto

class IframeBulkCreateTestCaseDto(BaseModel):
    """
      # noqa: E501
    """
    integration_id: StrictInt = Field(default=..., alias="integrationId")
    issue_key: StrictStr = Field(default=..., alias="issueKey")
    to_create: conlist(TestCaseCreateDto) = Field(default=..., alias="toCreate")
    __properties = ["integrationId", "issueKey", "toCreate"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IframeBulkCreateTestCaseDto:
        """Create an instance of IframeBulkCreateTestCaseDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in to_create (list)
        _items = []
        if self.to_create:
            for _item in self.to_create:
                if _item:
                    _items.append(_item.to_dict())
            _dict['toCreate'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IframeBulkCreateTestCaseDto:
        """Create an instance of IframeBulkCreateTestCaseDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IframeBulkCreateTestCaseDto.parse_obj(obj)

        _obj = IframeBulkCreateTestCaseDto.parse_obj({
            "integration_id": obj.get("integrationId"),
            "issue_key": obj.get("issueKey"),
            "to_create": [TestCaseCreateDto.from_dict(_item) for _item in obj.get("toCreate")] if obj.get("toCreate") is not None else None
        })
        return _obj


