# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ImportRequestStateDto(str, Enum):
    """
    
    """

    """
    allowed enum values
    """
    STORED = 'stored'
    PROCESSING = 'processing'
    PROCESSED = 'processed'
    ERROR = 'error'

    @classmethod
    def from_json(cls, json_str: str) -> ImportRequestStateDto:
        """Create an instance of ImportRequestStateDto from a JSON string"""
        return ImportRequestStateDto(json.loads(json_str))


