# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, StrictStr, conlist
from openapi_client.models.integration_operation_type_dto import IntegrationOperationTypeDto
from openapi_client.models.integration_routine_type_dto import IntegrationRoutineTypeDto
from openapi_client.models.integration_type_dto import IntegrationTypeDto

class IntegrationInfoDto(BaseModel):
    """
      # noqa: E501
    """
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    type: Optional[IntegrationTypeDto] = None
    operations: Optional[conlist(IntegrationOperationTypeDto)] = None
    routines: Optional[conlist(IntegrationRoutineTypeDto)] = None
    __properties = ["name", "description", "type", "operations", "routines"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IntegrationInfoDto:
        """Create an instance of IntegrationInfoDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IntegrationInfoDto:
        """Create an instance of IntegrationInfoDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IntegrationInfoDto.parse_obj(obj)

        _obj = IntegrationInfoDto.parse_obj({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "type": obj.get("type"),
            "operations": obj.get("operations"),
            "routines": obj.get("routines")
        })
        return _obj


