# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr

class IntegrationExportPatchDto(BaseModel):
    """
      # noqa: E501
    """
    disabled: Optional[StrictBool] = None
    disable_tc_create: Optional[StrictBool] = Field(default=None, alias="disableTcCreate")
    disable_launch_sync: Optional[StrictBool] = Field(default=None, alias="disableLaunchSync")
    project_key: Optional[StrictStr] = Field(default=None, alias="projectKey")
    tc_aql: Optional[StrictStr] = Field(default=None, alias="tcAql")
    launch_aql: Optional[StrictStr] = Field(default=None, alias="launchAql")
    sync_delay_sec: Optional[StrictInt] = Field(default=None, alias="syncDelaySec")
    settings: Optional[Dict[str, Any]] = None
    __properties = ["disabled", "disableTcCreate", "disableLaunchSync", "projectKey", "tcAql", "launchAql", "syncDelaySec", "settings"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> IntegrationExportPatchDto:
        """Create an instance of IntegrationExportPatchDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> IntegrationExportPatchDto:
        """Create an instance of IntegrationExportPatchDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return IntegrationExportPatchDto.parse_obj(obj)

        _obj = IntegrationExportPatchDto.parse_obj({
            "disabled": obj.get("disabled"),
            "disable_tc_create": obj.get("disableTcCreate"),
            "disable_launch_sync": obj.get("disableLaunchSync"),
            "project_key": obj.get("projectKey"),
            "tc_aql": obj.get("tcAql"),
            "launch_aql": obj.get("launchAql"),
            "sync_delay_sec": obj.get("syncDelaySec"),
            "settings": obj.get("settings")
        })
        return _obj


