# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from openapi_client.models.test_status_count import TestStatusCount

class LaunchMemberStatsDto(BaseModel):
    """
      # noqa: E501
    """
    assignee: Optional[StrictStr] = None
    statistic: Optional[conlist(TestStatusCount)] = None
    muted_count: Optional[StrictInt] = Field(default=None, alias="mutedCount")
    retried_count: Optional[StrictInt] = Field(default=None, alias="retriedCount")
    defects_count: Optional[StrictInt] = Field(default=None, alias="defectsCount")
    duration_sum: Optional[StrictInt] = Field(default=None, alias="durationSum")
    __properties = ["assignee", "statistic", "mutedCount", "retriedCount", "defectsCount", "durationSum"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LaunchMemberStatsDto:
        """Create an instance of LaunchMemberStatsDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in statistic (list)
        _items = []
        if self.statistic:
            for _item in self.statistic:
                if _item:
                    _items.append(_item.to_dict())
            _dict['statistic'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LaunchMemberStatsDto:
        """Create an instance of LaunchMemberStatsDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LaunchMemberStatsDto.parse_obj(obj)

        _obj = LaunchMemberStatsDto.parse_obj({
            "assignee": obj.get("assignee"),
            "statistic": [TestStatusCount.from_dict(_item) for _item in obj.get("statistic")] if obj.get("statistic") is not None else None,
            "muted_count": obj.get("mutedCount"),
            "retried_count": obj.get("retriedCount"),
            "defects_count": obj.get("defectsCount"),
            "duration_sum": obj.get("durationSum")
        })
        return _obj


