# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from openapi_client.models.launch_diff_test_result import LaunchDiffTestResult
from openapi_client.models.test_status import TestStatus

class LaunchDiffCell(BaseModel):
    """
      # noqa: E501
    """
    launch_id: Optional[StrictInt] = Field(default=None, alias="launchId")
    launch_name: Optional[StrictStr] = Field(default=None, alias="launchName")
    status: Optional[TestStatus] = None
    results: Optional[conlist(LaunchDiffTestResult, unique_items=True)] = None
    __properties = ["launchId", "launchName", "status", "results"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LaunchDiffCell:
        """Create an instance of LaunchDiffCell from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in results (list)
        _items = []
        if self.results:
            for _item in self.results:
                if _item:
                    _items.append(_item.to_dict())
            _dict['results'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LaunchDiffCell:
        """Create an instance of LaunchDiffCell from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LaunchDiffCell.parse_obj(obj)

        _obj = LaunchDiffCell.parse_obj({
            "launch_id": obj.get("launchId"),
            "launch_name": obj.get("launchName"),
            "status": obj.get("status"),
            "results": [LaunchDiffTestResult.from_dict(_item) for _item in obj.get("results")] if obj.get("results") is not None else None
        })
        return _obj


