# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from openapi_client.models.environment_set_dto import EnvironmentSetDto
from openapi_client.models.external_link_dto import ExternalLinkDto
from openapi_client.models.issue_dto import IssueDto
from openapi_client.models.launch_tag_dto import LaunchTagDto

class LaunchCopyRqDto(BaseModel):
    """
      # noqa: E501
    """
    launch_name: Optional[StrictStr] = Field(default=None, alias="launchName")
    tags: Optional[conlist(LaunchTagDto, unique_items=True)] = None
    links: Optional[conlist(ExternalLinkDto, unique_items=True)] = None
    issues: Optional[conlist(IssueDto, unique_items=True)] = None
    env_var_value_sets: Optional[conlist(EnvironmentSetDto)] = Field(default=None, alias="envVarValueSets")
    assignees: Optional[conlist(StrictStr, unique_items=True)] = None
    __properties = ["launchName", "tags", "links", "issues", "envVarValueSets", "assignees"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> LaunchCopyRqDto:
        """Create an instance of LaunchCopyRqDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item in self.tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in links (list)
        _items = []
        if self.links:
            for _item in self.links:
                if _item:
                    _items.append(_item.to_dict())
            _dict['links'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in issues (list)
        _items = []
        if self.issues:
            for _item in self.issues:
                if _item:
                    _items.append(_item.to_dict())
            _dict['issues'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in env_var_value_sets (list)
        _items = []
        if self.env_var_value_sets:
            for _item in self.env_var_value_sets:
                if _item:
                    _items.append(_item.to_dict())
            _dict['envVarValueSets'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> LaunchCopyRqDto:
        """Create an instance of LaunchCopyRqDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return LaunchCopyRqDto.parse_obj(obj)

        _obj = LaunchCopyRqDto.parse_obj({
            "launch_name": obj.get("launchName"),
            "tags": [LaunchTagDto.from_dict(_item) for _item in obj.get("tags")] if obj.get("tags") is not None else None,
            "links": [ExternalLinkDto.from_dict(_item) for _item in obj.get("links")] if obj.get("links") is not None else None,
            "issues": [IssueDto.from_dict(_item) for _item in obj.get("issues")] if obj.get("issues") is not None else None,
            "env_var_value_sets": [EnvironmentSetDto.from_dict(_item) for _item in obj.get("envVarValueSets")] if obj.get("envVarValueSets") is not None else None,
            "assignees": obj.get("assignees")
        })
        return _obj


