# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictInt, StrictStr
from openapi_client.models.role_dto import RoleDto

class MemberDto(BaseModel):
    """
      # noqa: E501
    """
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    role: Optional[RoleDto] = None
    __properties = ["id", "name", "role"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MemberDto:
        """Create an instance of MemberDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of role
        if self.role:
            _dict['role'] = self.role.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MemberDto:
        """Create an instance of MemberDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MemberDto.parse_obj(obj)

        _obj = MemberDto.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "role": RoleDto.from_dict(obj.get("role")) if obj.get("role") is not None else None
        })
        return _obj


