# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from openapi_client.models.issue_dto import IssueDto

class MuteDto(BaseModel):
    """
      # noqa: E501
    """
    id: Optional[StrictInt] = None
    test_case_id: Optional[StrictInt] = Field(default=None, alias="testCaseId")
    name: Optional[StrictStr] = None
    reason: Optional[StrictStr] = None
    reason_html: Optional[StrictStr] = Field(default=None, alias="reasonHtml")
    issues: Optional[conlist(IssueDto)] = None
    created_date: Optional[StrictInt] = Field(default=None, alias="createdDate")
    last_modified_date: Optional[StrictInt] = Field(default=None, alias="lastModifiedDate")
    created_by: Optional[StrictStr] = Field(default=None, alias="createdBy")
    last_modified_by: Optional[StrictStr] = Field(default=None, alias="lastModifiedBy")
    __properties = ["id", "testCaseId", "name", "reason", "reasonHtml", "issues", "createdDate", "lastModifiedDate", "createdBy", "lastModifiedBy"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MuteDto:
        """Create an instance of MuteDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in issues (list)
        _items = []
        if self.issues:
            for _item in self.issues:
                if _item:
                    _items.append(_item.to_dict())
            _dict['issues'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MuteDto:
        """Create an instance of MuteDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MuteDto.parse_obj(obj)

        _obj = MuteDto.parse_obj({
            "id": obj.get("id"),
            "test_case_id": obj.get("testCaseId"),
            "name": obj.get("name"),
            "reason": obj.get("reason"),
            "reason_html": obj.get("reasonHtml"),
            "issues": [IssueDto.from_dict(_item) for _item in obj.get("issues")] if obj.get("issues") is not None else None,
            "created_date": obj.get("createdDate"),
            "last_modified_date": obj.get("lastModifiedDate"),
            "created_by": obj.get("createdBy"),
            "last_modified_by": obj.get("lastModifiedBy")
        })
        return _obj


