# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class PermissionDto(str, Enum):
    """
    
    """

    """
    allowed enum values
    """
    PROJECT_COLON_CONFIGURE = 'project:configure'
    PROJECT_COLON_WRITE = 'project:write'
    PROJECT_COLON_COMMENT = 'project:comment'
    PROJECT_COLON_READ = 'project:read'

    @classmethod
    def from_json(cls, json_str: str) -> PermissionDto:
        """Create an instance of PermissionDto from a JSON string"""
        return PermissionDto(json.loads(json_str))


