# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr

class TestCaseCloneRqDto(BaseModel):
    """
      # noqa: E501
    """
    to_project_id: Optional[StrictInt] = Field(default=None, alias="toProjectId")
    workflow_id: Optional[StrictInt] = Field(default=None, alias="workflowId")
    status_id: Optional[StrictInt] = Field(default=None, alias="statusId")
    name_suffix: Optional[StrictStr] = Field(default=None, alias="nameSuffix")
    ignore_links: Optional[StrictBool] = Field(default=None, alias="ignoreLinks")
    ignore_cfv: Optional[StrictBool] = Field(default=None, alias="ignoreCfv")
    ignore_members: Optional[StrictBool] = Field(default=None, alias="ignoreMembers")
    ignore_tags: Optional[StrictBool] = Field(default=None, alias="ignoreTags")
    ignore_test_keys: Optional[StrictBool] = Field(default=None, alias="ignoreTestKeys")
    ignore_issue_links: Optional[StrictBool] = Field(default=None, alias="ignoreIssueLinks")
    ignore_parameters: Optional[StrictBool] = Field(default=None, alias="ignoreParameters")
    ignore_relations: Optional[StrictBool] = Field(default=None, alias="ignoreRelations")
    ignore_attachments: Optional[StrictBool] = Field(default=None, alias="ignoreAttachments")
    ignore_scenario: Optional[StrictBool] = Field(default=None, alias="ignoreScenario")
    __properties = ["toProjectId", "workflowId", "statusId", "nameSuffix", "ignoreLinks", "ignoreCfv", "ignoreMembers", "ignoreTags", "ignoreTestKeys", "ignoreIssueLinks", "ignoreParameters", "ignoreRelations", "ignoreAttachments", "ignoreScenario"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TestCaseCloneRqDto:
        """Create an instance of TestCaseCloneRqDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TestCaseCloneRqDto:
        """Create an instance of TestCaseCloneRqDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TestCaseCloneRqDto.parse_obj(obj)

        _obj = TestCaseCloneRqDto.parse_obj({
            "to_project_id": obj.get("toProjectId"),
            "workflow_id": obj.get("workflowId"),
            "status_id": obj.get("statusId"),
            "name_suffix": obj.get("nameSuffix"),
            "ignore_links": obj.get("ignoreLinks"),
            "ignore_cfv": obj.get("ignoreCfv"),
            "ignore_members": obj.get("ignoreMembers"),
            "ignore_tags": obj.get("ignoreTags"),
            "ignore_test_keys": obj.get("ignoreTestKeys"),
            "ignore_issue_links": obj.get("ignoreIssueLinks"),
            "ignore_parameters": obj.get("ignoreParameters"),
            "ignore_relations": obj.get("ignoreRelations"),
            "ignore_attachments": obj.get("ignoreAttachments"),
            "ignore_scenario": obj.get("ignoreScenario")
        })
        return _obj


