# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class TestLayerSchemaPatchDto(BaseModel):
    """
      # noqa: E501
    """
    key: Optional[StrictStr] = None
    test_layer_id: Optional[StrictInt] = Field(default=None, alias="testLayerId")
    __properties = ["key", "testLayerId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TestLayerSchemaPatchDto:
        """Create an instance of TestLayerSchemaPatchDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TestLayerSchemaPatchDto:
        """Create an instance of TestLayerSchemaPatchDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TestLayerSchemaPatchDto.parse_obj(obj)

        _obj = TestLayerSchemaPatchDto.parse_obj({
            "key": obj.get("key"),
            "test_layer_id": obj.get("testLayerId")
        })
        return _obj


