# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist
from openapi_client.models.custom_field_value_dto import CustomFieldValueDto
from openapi_client.models.test_case_tree_selection_dto import TestCaseTreeSelectionDto

class TestCaseBulkCfvDto(BaseModel):
    """
      # noqa: E501
    """
    selection: TestCaseTreeSelectionDto = Field(...)
    cfv: conlist(CustomFieldValueDto, unique_items=True) = Field(...)
    __properties = ["selection", "cfv"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TestCaseBulkCfvDto:
        """Create an instance of TestCaseBulkCfvDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of selection
        if self.selection:
            _dict['selection'] = self.selection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in cfv (list)
        _items = []
        if self.cfv:
            for _item in self.cfv:
                if _item:
                    _items.append(_item.to_dict())
            _dict['cfv'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TestCaseBulkCfvDto:
        """Create an instance of TestCaseBulkCfvDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TestCaseBulkCfvDto.parse_obj(obj)

        _obj = TestCaseBulkCfvDto.parse_obj({
            "selection": TestCaseTreeSelectionDto.from_dict(obj.get("selection")) if obj.get("selection") is not None else None,
            "cfv": [CustomFieldValueDto.from_dict(_item) for _item in obj.get("cfv")] if obj.get("cfv") is not None else None
        })
        return _obj


