# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, conlist
from openapi_client.models.custom_field_value_dto import CustomFieldValueDto
from openapi_client.models.external_link_dto import ExternalLinkDto
from openapi_client.models.member_dto import MemberDto
from openapi_client.models.test_case_scenario_dto import TestCaseScenarioDto
from openapi_client.models.test_tag_dto import TestTagDto

class TestCaseCreateDto(BaseModel):
    """
      # noqa: E501
    """
    project_id: StrictInt = Field(default=..., alias="projectId")
    name: StrictStr = Field(...)
    full_name: Optional[StrictStr] = Field(default=None, alias="fullName")
    description: Optional[StrictStr] = None
    precondition: Optional[StrictStr] = None
    expected_result: Optional[StrictStr] = Field(default=None, alias="expectedResult")
    deleted: Optional[StrictBool] = None
    automated: Optional[StrictBool] = None
    external: Optional[StrictBool] = None
    test_layer_id: Optional[StrictInt] = Field(default=None, alias="testLayerId")
    status_id: Optional[StrictInt] = Field(default=None, alias="statusId")
    workflow_id: Optional[StrictInt] = Field(default=None, alias="workflowId")
    scenario: Optional[TestCaseScenarioDto] = None
    tags: Optional[conlist(TestTagDto)] = None
    links: Optional[conlist(ExternalLinkDto)] = None
    custom_fields: Optional[conlist(CustomFieldValueDto)] = Field(default=None, alias="customFields")
    members: Optional[conlist(MemberDto)] = None
    __properties = ["projectId", "name", "fullName", "description", "precondition", "expectedResult", "deleted", "automated", "external", "testLayerId", "statusId", "workflowId", "scenario", "tags", "links", "customFields", "members"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TestCaseCreateDto:
        """Create an instance of TestCaseCreateDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of scenario
        if self.scenario:
            _dict['scenario'] = self.scenario.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item in self.tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in links (list)
        _items = []
        if self.links:
            for _item in self.links:
                if _item:
                    _items.append(_item.to_dict())
            _dict['links'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in custom_fields (list)
        _items = []
        if self.custom_fields:
            for _item in self.custom_fields:
                if _item:
                    _items.append(_item.to_dict())
            _dict['customFields'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in members (list)
        _items = []
        if self.members:
            for _item in self.members:
                if _item:
                    _items.append(_item.to_dict())
            _dict['members'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TestCaseCreateDto:
        """Create an instance of TestCaseCreateDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TestCaseCreateDto.parse_obj(obj)

        _obj = TestCaseCreateDto.parse_obj({
            "project_id": obj.get("projectId"),
            "name": obj.get("name"),
            "full_name": obj.get("fullName"),
            "description": obj.get("description"),
            "precondition": obj.get("precondition"),
            "expected_result": obj.get("expectedResult"),
            "deleted": obj.get("deleted"),
            "automated": obj.get("automated"),
            "external": obj.get("external"),
            "test_layer_id": obj.get("testLayerId"),
            "status_id": obj.get("statusId"),
            "workflow_id": obj.get("workflowId"),
            "scenario": TestCaseScenarioDto.from_dict(obj.get("scenario")) if obj.get("scenario") is not None else None,
            "tags": [TestTagDto.from_dict(_item) for _item in obj.get("tags")] if obj.get("tags") is not None else None,
            "links": [ExternalLinkDto.from_dict(_item) for _item in obj.get("links")] if obj.get("links") is not None else None,
            "custom_fields": [CustomFieldValueDto.from_dict(_item) for _item in obj.get("customFields")] if obj.get("customFields") is not None else None,
            "members": [MemberDto.from_dict(_item) for _item in obj.get("members")] if obj.get("members") is not None else None
        })
        return _obj


