# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class TestCaseUpdatePolicyDto(str, Enum):
    """
    
    """

    """
    allowed enum values
    """
    FROM_TEST_CASE = 'from_test_case'
    FROM_TEST_RESULT = 'from_test_result'

    @classmethod
    def from_json(cls, json_str: str) -> TestCaseUpdatePolicyDto:
        """Create an instance of TestCaseUpdatePolicyDto from a JSON string"""
        return TestCaseUpdatePolicyDto(json.loads(json_str))


