# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, validator
from openapi_client.models.widget_options_analytic_graph import WidgetOptionsAnalyticGraph
from openapi_client.models.widget_options_launch_list import WidgetOptionsLaunchList
from openapi_client.models.widget_options_markdown import WidgetOptionsMarkdown
from openapi_client.models.widget_options_tc_pie_chart import WidgetOptionsTcPieChart
from openapi_client.models.widget_options_tc_tree_map import WidgetOptionsTcTreeMap
from openapi_client.models.widget_options_top_tc import WidgetOptionsTopTc
from openapi_client.models.widget_options_trend import WidgetOptionsTrend
from typing import Union, Any, List, TYPE_CHECKING
from pydantic import StrictStr, Field

WIDGETCREATEDTOOPTIONS_ONE_OF_SCHEMAS = ["WidgetOptionsAnalyticGraph", "WidgetOptionsLaunchList", "WidgetOptionsMarkdown", "WidgetOptionsTcPieChart", "WidgetOptionsTcTreeMap", "WidgetOptionsTopTc", "WidgetOptionsTrend"]

class WidgetCreateDtoOptions(BaseModel):
    """
    WidgetCreateDtoOptions
    """
    # data type: WidgetOptionsAnalyticGraph
    oneof_schema_1_validator: Optional[WidgetOptionsAnalyticGraph] = None
    # data type: WidgetOptionsLaunchList
    oneof_schema_2_validator: Optional[WidgetOptionsLaunchList] = None
    # data type: WidgetOptionsMarkdown
    oneof_schema_3_validator: Optional[WidgetOptionsMarkdown] = None
    # data type: WidgetOptionsTcPieChart
    oneof_schema_4_validator: Optional[WidgetOptionsTcPieChart] = None
    # data type: WidgetOptionsTcTreeMap
    oneof_schema_5_validator: Optional[WidgetOptionsTcTreeMap] = None
    # data type: WidgetOptionsTopTc
    oneof_schema_6_validator: Optional[WidgetOptionsTopTc] = None
    # data type: WidgetOptionsTrend
    oneof_schema_7_validator: Optional[WidgetOptionsTrend] = None
    if TYPE_CHECKING:
        actual_instance: Union[WidgetOptionsAnalyticGraph, WidgetOptionsLaunchList, WidgetOptionsMarkdown, WidgetOptionsTcPieChart, WidgetOptionsTcTreeMap, WidgetOptionsTopTc, WidgetOptionsTrend]
    else:
        actual_instance: Any
    one_of_schemas: List[str] = Field(WIDGETCREATEDTOOPTIONS_ONE_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    discriminator_value_class_map = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = WidgetCreateDtoOptions.construct()
        error_messages = []
        match = 0
        # validate data type: WidgetOptionsAnalyticGraph
        if not isinstance(v, WidgetOptionsAnalyticGraph):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WidgetOptionsAnalyticGraph`")
        else:
            match += 1
        # validate data type: WidgetOptionsLaunchList
        if not isinstance(v, WidgetOptionsLaunchList):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WidgetOptionsLaunchList`")
        else:
            match += 1
        # validate data type: WidgetOptionsMarkdown
        if not isinstance(v, WidgetOptionsMarkdown):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WidgetOptionsMarkdown`")
        else:
            match += 1
        # validate data type: WidgetOptionsTcPieChart
        if not isinstance(v, WidgetOptionsTcPieChart):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WidgetOptionsTcPieChart`")
        else:
            match += 1
        # validate data type: WidgetOptionsTcTreeMap
        if not isinstance(v, WidgetOptionsTcTreeMap):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WidgetOptionsTcTreeMap`")
        else:
            match += 1
        # validate data type: WidgetOptionsTopTc
        if not isinstance(v, WidgetOptionsTopTc):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WidgetOptionsTopTc`")
        else:
            match += 1
        # validate data type: WidgetOptionsTrend
        if not isinstance(v, WidgetOptionsTrend):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WidgetOptionsTrend`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in WidgetCreateDtoOptions with oneOf schemas: WidgetOptionsAnalyticGraph, WidgetOptionsLaunchList, WidgetOptionsMarkdown, WidgetOptionsTcPieChart, WidgetOptionsTcTreeMap, WidgetOptionsTopTc, WidgetOptionsTrend. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in WidgetCreateDtoOptions with oneOf schemas: WidgetOptionsAnalyticGraph, WidgetOptionsLaunchList, WidgetOptionsMarkdown, WidgetOptionsTcPieChart, WidgetOptionsTcTreeMap, WidgetOptionsTopTc, WidgetOptionsTrend. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> WidgetCreateDtoOptions:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> WidgetCreateDtoOptions:
        """Returns the object represented by the json string"""
        instance = WidgetCreateDtoOptions.construct()
        error_messages = []
        match = 0

        # deserialize data into WidgetOptionsAnalyticGraph
        try:
            instance.actual_instance = WidgetOptionsAnalyticGraph.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WidgetOptionsLaunchList
        try:
            instance.actual_instance = WidgetOptionsLaunchList.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WidgetOptionsMarkdown
        try:
            instance.actual_instance = WidgetOptionsMarkdown.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WidgetOptionsTcPieChart
        try:
            instance.actual_instance = WidgetOptionsTcPieChart.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WidgetOptionsTcTreeMap
        try:
            instance.actual_instance = WidgetOptionsTcTreeMap.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WidgetOptionsTopTc
        try:
            instance.actual_instance = WidgetOptionsTopTc.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WidgetOptionsTrend
        try:
            instance.actual_instance = WidgetOptionsTrend.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into WidgetCreateDtoOptions with oneOf schemas: WidgetOptionsAnalyticGraph, WidgetOptionsLaunchList, WidgetOptionsMarkdown, WidgetOptionsTcPieChart, WidgetOptionsTcTreeMap, WidgetOptionsTopTc, WidgetOptionsTrend. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into WidgetCreateDtoOptions with oneOf schemas: WidgetOptionsAnalyticGraph, WidgetOptionsLaunchList, WidgetOptionsMarkdown, WidgetOptionsTcPieChart, WidgetOptionsTcTreeMap, WidgetOptionsTopTc, WidgetOptionsTrend. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())


