# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import BaseModel, Field, StrictStr

from typing import TYPE_CHECKING
from importlib import import_module
if TYPE_CHECKING:
    from openapi_client.models.widget_options_analytic_graph import WidgetOptionsAnalyticGraph
    from openapi_client.models.widget_options_launch_list import WidgetOptionsLaunchList
    from openapi_client.models.widget_options_markdown import WidgetOptionsMarkdown
    from openapi_client.models.widget_options_tc_pie_chart import WidgetOptionsTcPieChart
    from openapi_client.models.widget_options_tc_tree_map import WidgetOptionsTcTreeMap
    from openapi_client.models.widget_options_top_tc import WidgetOptionsTopTc
    from openapi_client.models.widget_options_trend import WidgetOptionsTrend

class WidgetOptions(BaseModel):
    """
    WidgetOptions
    """
    type: StrictStr = Field(...)
    __properties = ["type"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    # JSON field name that stores the object type
    __discriminator_property_name = 'type'

    # discriminator mappings
    __discriminator_value_class_map = {
        'WidgetOptionsAnalyticGraph': 'WidgetOptionsAnalyticGraph',
        'WidgetOptionsLaunchList': 'WidgetOptionsLaunchList',
        'WidgetOptionsMarkdown': 'WidgetOptionsMarkdown',
        'WidgetOptionsTcPieChart': 'WidgetOptionsTcPieChart',
        'WidgetOptionsTcTreeMap': 'WidgetOptionsTcTreeMap',
        'WidgetOptionsTopTc': 'WidgetOptionsTopTc',
        'WidgetOptionsTrend': 'WidgetOptionsTrend'
    }

    @classmethod
    def get_discriminator_value(cls, obj: dict) -> str:
        """Returns the discriminator value (object type) of the data"""
        discriminator_value = obj[cls.__discriminator_property_name]
        if discriminator_value:
            return cls.__discriminator_value_class_map.get(discriminator_value)
        else:
            return None

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Union(WidgetOptionsAnalyticGraph, WidgetOptionsLaunchList, WidgetOptionsMarkdown, WidgetOptionsTcPieChart, WidgetOptionsTcTreeMap, WidgetOptionsTopTc, WidgetOptionsTrend):
        """Create an instance of WidgetOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Union(WidgetOptionsAnalyticGraph, WidgetOptionsLaunchList, WidgetOptionsMarkdown, WidgetOptionsTcPieChart, WidgetOptionsTcTreeMap, WidgetOptionsTopTc, WidgetOptionsTrend):
        """Create an instance of WidgetOptions from a dict"""
        # look up the object type based on discriminator mapping
        object_type = cls.get_discriminator_value(obj)
        if object_type ==  'WidgetOptionsAnalyticGraph':
            return import_module("openapi_client.models.widget_options_analytic_graph").WidgetOptionsAnalyticGraph.from_dict(obj)
        if object_type ==  'WidgetOptionsLaunchList':
            return import_module("openapi_client.models.widget_options_launch_list").WidgetOptionsLaunchList.from_dict(obj)
        if object_type ==  'WidgetOptionsMarkdown':
            return import_module("openapi_client.models.widget_options_markdown").WidgetOptionsMarkdown.from_dict(obj)
        if object_type ==  'WidgetOptionsTcPieChart':
            return import_module("openapi_client.models.widget_options_tc_pie_chart").WidgetOptionsTcPieChart.from_dict(obj)
        if object_type ==  'WidgetOptionsTcTreeMap':
            return import_module("openapi_client.models.widget_options_tc_tree_map").WidgetOptionsTcTreeMap.from_dict(obj)
        if object_type ==  'WidgetOptionsTopTc':
            return import_module("openapi_client.models.widget_options_top_tc").WidgetOptionsTopTc.from_dict(obj)
        if object_type ==  'WidgetOptionsTrend':
            return import_module("openapi_client.models.widget_options_trend").WidgetOptionsTrend.from_dict(obj)
        raise ValueError("WidgetOptions failed to lookup discriminator value from " +
                            json.dumps(obj) + ". Discriminator property name: " + cls.__discriminator_property_name +
                            ", mapping: " + json.dumps(cls.__discriminator_value_class_map))


