[pytest]
addopts =
    --showlocals -vv
    -p no:faulthandler
    --force-flaky --max-runs=3  --min-passes=1
    --cache-clear
    --cov=web --cov-report term-missing --cov-config=.coveragerc
    --code-highlight=yes --showlocals
    --alluredir=allure-report
; --cov-report term-missing:skip-covered
console_output_style = modern
testpaths = tests
python_files = test_*.py
norecursedirs = .* venv .venv src *.egg dist build .git xslt_templates .idea
log_cli = true
log_cli_level = INFO
# https://docs.python.org/3/library/logging.html#module-logging
log_cli_format = [%(levelname)s] %(message)s (%(filename)s:%(lineno)s)
log_cli_date_format = %Y-%m-%d %H:%M:%S
filterwarnings =
    ignore::DeprecationWarning
markers =
    accounts: module