# coding: utf-8

"""
    allure-report-service

    Branch **HEAD**  Commit **a1bfd54f15d10d0c2ee0872855b02025deb3ec3a**

    The version of the OpenAPI document: 4.23.0-dashboards.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError

from typing_extensions import Annotated
from pydantic import Field, StrictInt, StrictStr, conint, conlist

from typing import List, Optional

from openapi_client.models.job_test_cases_stat_dto import JobTestCasesStatDto
from openapi_client.models.page_id_and_name_only_dto import PageIdAndNameOnlyDto
from openapi_client.models.page_test_case_tree_group_dto import PageTestCaseTreeGroupDto
from openapi_client.models.page_test_case_tree_leaf_dto import PageTestCaseTreeLeafDto
from openapi_client.models.test_case_run_by_stats import TestCaseRunByStats
from openapi_client.models.test_case_tree_filter_count_dto import TestCaseTreeFilterCountDto
from openapi_client.models.test_case_tree_group_add_dto import TestCaseTreeGroupAddDto
from openapi_client.models.test_case_tree_group_dto import TestCaseTreeGroupDto
from openapi_client.models.test_case_tree_group_rename_dto import TestCaseTreeGroupRenameDto
from openapi_client.models.test_case_tree_leaf_add_dto import TestCaseTreeLeafAddDto
from openapi_client.models.test_case_tree_leaf_dto import TestCaseTreeLeafDto
from openapi_client.models.test_case_tree_leaf_rename_dto import TestCaseTreeLeafRenameDto
from openapi_client.models.test_case_tree_run_stat_request_dto import TestCaseTreeRunStatRequestDto

from openapi_client.api_client import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class TestCaseTreeControllerApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def add_group1(self, project_id : StrictInt, test_case_tree_group_add_dto : TestCaseTreeGroupAddDto, filter_id : Optional[StrictInt] = None, search : Optional[StrictStr] = None, tree_id : Optional[StrictInt] = None, path : Optional[conlist(StrictInt)] = None, base_rql : Optional[StrictStr] = None, **kwargs) -> TestCaseTreeGroupDto:  # noqa: E501
        """Add a new group (AQL)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.add_group1(project_id, test_case_tree_group_add_dto, filter_id, search, tree_id, path, base_rql, async_req=True)
        >>> result = thread.get()

        :param project_id: (required)
        :type project_id: int
        :param test_case_tree_group_add_dto: (required)
        :type test_case_tree_group_add_dto: TestCaseTreeGroupAddDto
        :param filter_id:
        :type filter_id: int
        :param search:
        :type search: str
        :param tree_id:
        :type tree_id: int
        :param path:
        :type path: List[int]
        :param base_rql:
        :type base_rql: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: TestCaseTreeGroupDto
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the add_group1_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.add_group1_with_http_info(project_id, test_case_tree_group_add_dto, filter_id, search, tree_id, path, base_rql, **kwargs)  # noqa: E501

    @validate_arguments
    def add_group1_with_http_info(self, project_id : StrictInt, test_case_tree_group_add_dto : TestCaseTreeGroupAddDto, filter_id : Optional[StrictInt] = None, search : Optional[StrictStr] = None, tree_id : Optional[StrictInt] = None, path : Optional[conlist(StrictInt)] = None, base_rql : Optional[StrictStr] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Add a new group (AQL)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.add_group1_with_http_info(project_id, test_case_tree_group_add_dto, filter_id, search, tree_id, path, base_rql, async_req=True)
        >>> result = thread.get()

        :param project_id: (required)
        :type project_id: int
        :param test_case_tree_group_add_dto: (required)
        :type test_case_tree_group_add_dto: TestCaseTreeGroupAddDto
        :param filter_id:
        :type filter_id: int
        :param search:
        :type search: str
        :param tree_id:
        :type tree_id: int
        :param path:
        :type path: List[int]
        :param base_rql:
        :type base_rql: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(TestCaseTreeGroupDto, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'project_id',
            'test_case_tree_group_add_dto',
            'filter_id',
            'search',
            'tree_id',
            'path',
            'base_rql'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_group1" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('project_id') is not None:  # noqa: E501
            _query_params.append(('projectId', _params['project_id']))

        if _params.get('filter_id') is not None:  # noqa: E501
            _query_params.append(('filterId', _params['filter_id']))

        if _params.get('search') is not None:  # noqa: E501
            _query_params.append(('search', _params['search']))

        if _params.get('tree_id') is not None:  # noqa: E501
            _query_params.append(('treeId', _params['tree_id']))

        if _params.get('path') is not None:  # noqa: E501
            _query_params.append(('path', _params['path']))
            _collection_formats['path'] = 'multi'

        if _params.get('base_rql') is not None:  # noqa: E501
            _query_params.append(('baseRql', _params['base_rql']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['test_case_tree_group_add_dto'] is not None:
            _body_params = _params['test_case_tree_group_add_dto']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "TestCaseTreeGroupDto",
        }

        return self.api_client.call_api(
            '/testcasetree/group', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def add_leaf(self, project_id : StrictInt, test_case_tree_leaf_add_dto : TestCaseTreeLeafAddDto, tree_id : Optional[StrictInt] = None, path : Optional[conlist(StrictInt)] = None, **kwargs) -> TestCaseTreeLeafDto:  # noqa: E501
        """Add a new group  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.add_leaf(project_id, test_case_tree_leaf_add_dto, tree_id, path, async_req=True)
        >>> result = thread.get()

        :param project_id: (required)
        :type project_id: int
        :param test_case_tree_leaf_add_dto: (required)
        :type test_case_tree_leaf_add_dto: TestCaseTreeLeafAddDto
        :param tree_id:
        :type tree_id: int
        :param path:
        :type path: List[int]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: TestCaseTreeLeafDto
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the add_leaf_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.add_leaf_with_http_info(project_id, test_case_tree_leaf_add_dto, tree_id, path, **kwargs)  # noqa: E501

    @validate_arguments
    def add_leaf_with_http_info(self, project_id : StrictInt, test_case_tree_leaf_add_dto : TestCaseTreeLeafAddDto, tree_id : Optional[StrictInt] = None, path : Optional[conlist(StrictInt)] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Add a new group  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.add_leaf_with_http_info(project_id, test_case_tree_leaf_add_dto, tree_id, path, async_req=True)
        >>> result = thread.get()

        :param project_id: (required)
        :type project_id: int
        :param test_case_tree_leaf_add_dto: (required)
        :type test_case_tree_leaf_add_dto: TestCaseTreeLeafAddDto
        :param tree_id:
        :type tree_id: int
        :param path:
        :type path: List[int]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(TestCaseTreeLeafDto, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'project_id',
            'test_case_tree_leaf_add_dto',
            'tree_id',
            'path'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_leaf" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('project_id') is not None:  # noqa: E501
            _query_params.append(('projectId', _params['project_id']))

        if _params.get('tree_id') is not None:  # noqa: E501
            _query_params.append(('treeId', _params['tree_id']))

        if _params.get('path') is not None:  # noqa: E501
            _query_params.append(('path', _params['path']))
            _collection_formats['path'] = 'multi'

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['test_case_tree_leaf_add_dto'] is not None:
            _body_params = _params['test_case_tree_leaf_add_dto']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "TestCaseTreeLeafDto",
        }

        return self.api_client.call_api(
            '/testcasetree/leaf', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def count_leaves2(self, project_id : StrictInt, search : Optional[StrictStr] = None, tree_id : Optional[StrictInt] = None, filter_id : Optional[StrictInt] = None, path : Optional[conlist(StrictInt)] = None, **kwargs) -> TestCaseTreeFilterCountDto:  # noqa: E501
        """Count all tree leaves for given path and filter  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.count_leaves2(project_id, search, tree_id, filter_id, path, async_req=True)
        >>> result = thread.get()

        :param project_id: (required)
        :type project_id: int
        :param search:
        :type search: str
        :param tree_id:
        :type tree_id: int
        :param filter_id:
        :type filter_id: int
        :param path:
        :type path: List[int]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: TestCaseTreeFilterCountDto
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the count_leaves2_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.count_leaves2_with_http_info(project_id, search, tree_id, filter_id, path, **kwargs)  # noqa: E501

    @validate_arguments
    def count_leaves2_with_http_info(self, project_id : StrictInt, search : Optional[StrictStr] = None, tree_id : Optional[StrictInt] = None, filter_id : Optional[StrictInt] = None, path : Optional[conlist(StrictInt)] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Count all tree leaves for given path and filter  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.count_leaves2_with_http_info(project_id, search, tree_id, filter_id, path, async_req=True)
        >>> result = thread.get()

        :param project_id: (required)
        :type project_id: int
        :param search:
        :type search: str
        :param tree_id:
        :type tree_id: int
        :param filter_id:
        :type filter_id: int
        :param path:
        :type path: List[int]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(TestCaseTreeFilterCountDto, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'project_id',
            'search',
            'tree_id',
            'filter_id',
            'path'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method count_leaves2" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('project_id') is not None:  # noqa: E501
            _query_params.append(('projectId', _params['project_id']))

        if _params.get('search') is not None:  # noqa: E501
            _query_params.append(('search', _params['search']))

        if _params.get('tree_id') is not None:  # noqa: E501
            _query_params.append(('treeId', _params['tree_id']))

        if _params.get('filter_id') is not None:  # noqa: E501
            _query_params.append(('filterId', _params['filter_id']))

        if _params.get('path') is not None:  # noqa: E501
            _query_params.append(('path', _params['path']))
            _collection_formats['path'] = 'multi'

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "TestCaseTreeFilterCountDto",
        }

        return self.api_client.call_api(
            '/testcasetree/countleaves', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def get_groups21(self, project_id : StrictInt, search : Optional[StrictStr] = None, tree_id : Optional[StrictInt] = None, filter_id : Optional[StrictInt] = None, path : Optional[conlist(StrictInt)] = None, page : Annotated[Optional[conint(strict=True, ge=0)], Field(description="Zero-based page index (0..N)")] = None, size : Annotated[Optional[conint(strict=True, ge=1)], Field(description="The size of the page to be returned")] = None, sort : Annotated[Optional[conlist(StrictStr)], Field(description="Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.")] = None, base_rql : Optional[StrictStr] = None, **kwargs) -> PageTestCaseTreeGroupDto:  # noqa: E501
        """Find tree groups for node (AQL)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_groups21(project_id, search, tree_id, filter_id, path, page, size, sort, base_rql, async_req=True)
        >>> result = thread.get()

        :param project_id: (required)
        :type project_id: int
        :param search:
        :type search: str
        :param tree_id:
        :type tree_id: int
        :param filter_id:
        :type filter_id: int
        :param path:
        :type path: List[int]
        :param page: Zero-based page index (0..N)
        :type page: int
        :param size: The size of the page to be returned
        :type size: int
        :param sort: Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
        :type sort: List[str]
        :param base_rql:
        :type base_rql: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: PageTestCaseTreeGroupDto
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_groups21_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_groups21_with_http_info(project_id, search, tree_id, filter_id, path, page, size, sort, base_rql, **kwargs)  # noqa: E501

    @validate_arguments
    def get_groups21_with_http_info(self, project_id : StrictInt, search : Optional[StrictStr] = None, tree_id : Optional[StrictInt] = None, filter_id : Optional[StrictInt] = None, path : Optional[conlist(StrictInt)] = None, page : Annotated[Optional[conint(strict=True, ge=0)], Field(description="Zero-based page index (0..N)")] = None, size : Annotated[Optional[conint(strict=True, ge=1)], Field(description="The size of the page to be returned")] = None, sort : Annotated[Optional[conlist(StrictStr)], Field(description="Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.")] = None, base_rql : Optional[StrictStr] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Find tree groups for node (AQL)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_groups21_with_http_info(project_id, search, tree_id, filter_id, path, page, size, sort, base_rql, async_req=True)
        >>> result = thread.get()

        :param project_id: (required)
        :type project_id: int
        :param search:
        :type search: str
        :param tree_id:
        :type tree_id: int
        :param filter_id:
        :type filter_id: int
        :param path:
        :type path: List[int]
        :param page: Zero-based page index (0..N)
        :type page: int
        :param size: The size of the page to be returned
        :type size: int
        :param sort: Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
        :type sort: List[str]
        :param base_rql:
        :type base_rql: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(PageTestCaseTreeGroupDto, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'project_id',
            'search',
            'tree_id',
            'filter_id',
            'path',
            'page',
            'size',
            'sort',
            'base_rql'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_groups21" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('project_id') is not None:  # noqa: E501
            _query_params.append(('projectId', _params['project_id']))

        if _params.get('search') is not None:  # noqa: E501
            _query_params.append(('search', _params['search']))

        if _params.get('tree_id') is not None:  # noqa: E501
            _query_params.append(('treeId', _params['tree_id']))

        if _params.get('filter_id') is not None:  # noqa: E501
            _query_params.append(('filterId', _params['filter_id']))

        if _params.get('path') is not None:  # noqa: E501
            _query_params.append(('path', _params['path']))
            _collection_formats['path'] = 'multi'

        if _params.get('page') is not None:  # noqa: E501
            _query_params.append(('page', _params['page']))

        if _params.get('size') is not None:  # noqa: E501
            _query_params.append(('size', _params['size']))

        if _params.get('sort') is not None:  # noqa: E501
            _query_params.append(('sort', _params['sort']))
            _collection_formats['sort'] = 'multi'

        if _params.get('base_rql') is not None:  # noqa: E501
            _query_params.append(('baseRql', _params['base_rql']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "PageTestCaseTreeGroupDto",
        }

        return self.api_client.call_api(
            '/testcasetree/group', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def get_jobs_info(self, test_case_tree_run_stat_request_dto : TestCaseTreeRunStatRequestDto, **kwargs) -> List[JobTestCasesStatDto]:  # noqa: E501
        """Get information about jobs that will be used to run selected test cases  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_jobs_info(test_case_tree_run_stat_request_dto, async_req=True)
        >>> result = thread.get()

        :param test_case_tree_run_stat_request_dto: (required)
        :type test_case_tree_run_stat_request_dto: TestCaseTreeRunStatRequestDto
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: List[JobTestCasesStatDto]
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_jobs_info_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_jobs_info_with_http_info(test_case_tree_run_stat_request_dto, **kwargs)  # noqa: E501

    @validate_arguments
    def get_jobs_info_with_http_info(self, test_case_tree_run_stat_request_dto : TestCaseTreeRunStatRequestDto, **kwargs) -> ApiResponse:  # noqa: E501
        """Get information about jobs that will be used to run selected test cases  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_jobs_info_with_http_info(test_case_tree_run_stat_request_dto, async_req=True)
        >>> result = thread.get()

        :param test_case_tree_run_stat_request_dto: (required)
        :type test_case_tree_run_stat_request_dto: TestCaseTreeRunStatRequestDto
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(List[JobTestCasesStatDto], status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'test_case_tree_run_stat_request_dto'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_jobs_info" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['test_case_tree_run_stat_request_dto'] is not None:
            _body_params = _params['test_case_tree_run_stat_request_dto']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "List[JobTestCasesStatDto]",
        }

        return self.api_client.call_api(
            '/testcasetree/job', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def get_leaves1(self, project_id : StrictInt, search : Optional[StrictStr] = None, tree_id : Optional[StrictInt] = None, filter_id : Optional[StrictInt] = None, path : Optional[conlist(StrictInt)] = None, page : Annotated[Optional[conint(strict=True, ge=0)], Field(description="Zero-based page index (0..N)")] = None, size : Annotated[Optional[conint(strict=True, ge=1)], Field(description="The size of the page to be returned")] = None, sort : Annotated[Optional[conlist(StrictStr)], Field(description="Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.")] = None, base_rql : Optional[StrictStr] = None, **kwargs) -> PageTestCaseTreeLeafDto:  # noqa: E501
        """Find tree leaves for node (AQL)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_leaves1(project_id, search, tree_id, filter_id, path, page, size, sort, base_rql, async_req=True)
        >>> result = thread.get()

        :param project_id: (required)
        :type project_id: int
        :param search:
        :type search: str
        :param tree_id:
        :type tree_id: int
        :param filter_id:
        :type filter_id: int
        :param path:
        :type path: List[int]
        :param page: Zero-based page index (0..N)
        :type page: int
        :param size: The size of the page to be returned
        :type size: int
        :param sort: Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
        :type sort: List[str]
        :param base_rql:
        :type base_rql: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: PageTestCaseTreeLeafDto
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_leaves1_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_leaves1_with_http_info(project_id, search, tree_id, filter_id, path, page, size, sort, base_rql, **kwargs)  # noqa: E501

    @validate_arguments
    def get_leaves1_with_http_info(self, project_id : StrictInt, search : Optional[StrictStr] = None, tree_id : Optional[StrictInt] = None, filter_id : Optional[StrictInt] = None, path : Optional[conlist(StrictInt)] = None, page : Annotated[Optional[conint(strict=True, ge=0)], Field(description="Zero-based page index (0..N)")] = None, size : Annotated[Optional[conint(strict=True, ge=1)], Field(description="The size of the page to be returned")] = None, sort : Annotated[Optional[conlist(StrictStr)], Field(description="Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.")] = None, base_rql : Optional[StrictStr] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Find tree leaves for node (AQL)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_leaves1_with_http_info(project_id, search, tree_id, filter_id, path, page, size, sort, base_rql, async_req=True)
        >>> result = thread.get()

        :param project_id: (required)
        :type project_id: int
        :param search:
        :type search: str
        :param tree_id:
        :type tree_id: int
        :param filter_id:
        :type filter_id: int
        :param path:
        :type path: List[int]
        :param page: Zero-based page index (0..N)
        :type page: int
        :param size: The size of the page to be returned
        :type size: int
        :param sort: Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
        :type sort: List[str]
        :param base_rql:
        :type base_rql: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(PageTestCaseTreeLeafDto, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'project_id',
            'search',
            'tree_id',
            'filter_id',
            'path',
            'page',
            'size',
            'sort',
            'base_rql'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_leaves1" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('project_id') is not None:  # noqa: E501
            _query_params.append(('projectId', _params['project_id']))

        if _params.get('search') is not None:  # noqa: E501
            _query_params.append(('search', _params['search']))

        if _params.get('tree_id') is not None:  # noqa: E501
            _query_params.append(('treeId', _params['tree_id']))

        if _params.get('filter_id') is not None:  # noqa: E501
            _query_params.append(('filterId', _params['filter_id']))

        if _params.get('path') is not None:  # noqa: E501
            _query_params.append(('path', _params['path']))
            _collection_formats['path'] = 'multi'

        if _params.get('page') is not None:  # noqa: E501
            _query_params.append(('page', _params['page']))

        if _params.get('size') is not None:  # noqa: E501
            _query_params.append(('size', _params['size']))

        if _params.get('sort') is not None:  # noqa: E501
            _query_params.append(('sort', _params['sort']))
            _collection_formats['sort'] = 'multi'

        if _params.get('base_rql') is not None:  # noqa: E501
            _query_params.append(('baseRql', _params['base_rql']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "PageTestCaseTreeLeafDto",
        }

        return self.api_client.call_api(
            '/testcasetree/leaf', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def get_run_stats(self, test_case_tree_run_stat_request_dto : TestCaseTreeRunStatRequestDto, **kwargs) -> TestCaseRunByStats:  # noqa: E501
        """Get run information  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_run_stats(test_case_tree_run_stat_request_dto, async_req=True)
        >>> result = thread.get()

        :param test_case_tree_run_stat_request_dto: (required)
        :type test_case_tree_run_stat_request_dto: TestCaseTreeRunStatRequestDto
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: TestCaseRunByStats
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the get_run_stats_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.get_run_stats_with_http_info(test_case_tree_run_stat_request_dto, **kwargs)  # noqa: E501

    @validate_arguments
    def get_run_stats_with_http_info(self, test_case_tree_run_stat_request_dto : TestCaseTreeRunStatRequestDto, **kwargs) -> ApiResponse:  # noqa: E501
        """Get run information  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.get_run_stats_with_http_info(test_case_tree_run_stat_request_dto, async_req=True)
        >>> result = thread.get()

        :param test_case_tree_run_stat_request_dto: (required)
        :type test_case_tree_run_stat_request_dto: TestCaseTreeRunStatRequestDto
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(TestCaseRunByStats, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'test_case_tree_run_stat_request_dto'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_run_stats" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['test_case_tree_run_stat_request_dto'] is not None:
            _body_params = _params['test_case_tree_run_stat_request_dto']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "TestCaseRunByStats",
        }

        return self.api_client.call_api(
            '/testcasetree/runstats', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def rename_group1(self, project_id : StrictInt, test_case_tree_group_rename_dto : TestCaseTreeGroupRenameDto, filter_id : Optional[StrictInt] = None, search : Optional[StrictStr] = None, tree_id : Optional[StrictInt] = None, path : Optional[conlist(StrictInt)] = None, base_rql : Optional[StrictStr] = None, **kwargs) -> TestCaseTreeGroupDto:  # noqa: E501
        """Rename tree group (AQL)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.rename_group1(project_id, test_case_tree_group_rename_dto, filter_id, search, tree_id, path, base_rql, async_req=True)
        >>> result = thread.get()

        :param project_id: (required)
        :type project_id: int
        :param test_case_tree_group_rename_dto: (required)
        :type test_case_tree_group_rename_dto: TestCaseTreeGroupRenameDto
        :param filter_id:
        :type filter_id: int
        :param search:
        :type search: str
        :param tree_id:
        :type tree_id: int
        :param path:
        :type path: List[int]
        :param base_rql:
        :type base_rql: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: TestCaseTreeGroupDto
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the rename_group1_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.rename_group1_with_http_info(project_id, test_case_tree_group_rename_dto, filter_id, search, tree_id, path, base_rql, **kwargs)  # noqa: E501

    @validate_arguments
    def rename_group1_with_http_info(self, project_id : StrictInt, test_case_tree_group_rename_dto : TestCaseTreeGroupRenameDto, filter_id : Optional[StrictInt] = None, search : Optional[StrictStr] = None, tree_id : Optional[StrictInt] = None, path : Optional[conlist(StrictInt)] = None, base_rql : Optional[StrictStr] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Rename tree group (AQL)  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.rename_group1_with_http_info(project_id, test_case_tree_group_rename_dto, filter_id, search, tree_id, path, base_rql, async_req=True)
        >>> result = thread.get()

        :param project_id: (required)
        :type project_id: int
        :param test_case_tree_group_rename_dto: (required)
        :type test_case_tree_group_rename_dto: TestCaseTreeGroupRenameDto
        :param filter_id:
        :type filter_id: int
        :param search:
        :type search: str
        :param tree_id:
        :type tree_id: int
        :param path:
        :type path: List[int]
        :param base_rql:
        :type base_rql: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(TestCaseTreeGroupDto, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'project_id',
            'test_case_tree_group_rename_dto',
            'filter_id',
            'search',
            'tree_id',
            'path',
            'base_rql'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method rename_group1" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('project_id') is not None:  # noqa: E501
            _query_params.append(('projectId', _params['project_id']))

        if _params.get('filter_id') is not None:  # noqa: E501
            _query_params.append(('filterId', _params['filter_id']))

        if _params.get('search') is not None:  # noqa: E501
            _query_params.append(('search', _params['search']))

        if _params.get('tree_id') is not None:  # noqa: E501
            _query_params.append(('treeId', _params['tree_id']))

        if _params.get('path') is not None:  # noqa: E501
            _query_params.append(('path', _params['path']))
            _collection_formats['path'] = 'multi'

        if _params.get('base_rql') is not None:  # noqa: E501
            _query_params.append(('baseRql', _params['base_rql']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['test_case_tree_group_rename_dto'] is not None:
            _body_params = _params['test_case_tree_group_rename_dto']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "TestCaseTreeGroupDto",
        }

        return self.api_client.call_api(
            '/testcasetree/group/rename', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def rename_leaf(self, project_id : StrictInt, leaf_id : StrictInt, test_case_tree_leaf_rename_dto : TestCaseTreeLeafRenameDto, **kwargs) -> TestCaseTreeLeafDto:  # noqa: E501
        """Rename tree leaf  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.rename_leaf(project_id, leaf_id, test_case_tree_leaf_rename_dto, async_req=True)
        >>> result = thread.get()

        :param project_id: (required)
        :type project_id: int
        :param leaf_id: (required)
        :type leaf_id: int
        :param test_case_tree_leaf_rename_dto: (required)
        :type test_case_tree_leaf_rename_dto: TestCaseTreeLeafRenameDto
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: TestCaseTreeLeafDto
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the rename_leaf_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.rename_leaf_with_http_info(project_id, leaf_id, test_case_tree_leaf_rename_dto, **kwargs)  # noqa: E501

    @validate_arguments
    def rename_leaf_with_http_info(self, project_id : StrictInt, leaf_id : StrictInt, test_case_tree_leaf_rename_dto : TestCaseTreeLeafRenameDto, **kwargs) -> ApiResponse:  # noqa: E501
        """Rename tree leaf  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.rename_leaf_with_http_info(project_id, leaf_id, test_case_tree_leaf_rename_dto, async_req=True)
        >>> result = thread.get()

        :param project_id: (required)
        :type project_id: int
        :param leaf_id: (required)
        :type leaf_id: int
        :param test_case_tree_leaf_rename_dto: (required)
        :type test_case_tree_leaf_rename_dto: TestCaseTreeLeafRenameDto
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(TestCaseTreeLeafDto, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'project_id',
            'leaf_id',
            'test_case_tree_leaf_rename_dto'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method rename_leaf" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('project_id') is not None:  # noqa: E501
            _query_params.append(('projectId', _params['project_id']))

        if _params.get('leaf_id') is not None:  # noqa: E501
            _query_params.append(('leafId', _params['leaf_id']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['test_case_tree_leaf_rename_dto'] is not None:
            _body_params = _params['test_case_tree_leaf_rename_dto']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "TestCaseTreeLeafDto",
        }

        return self.api_client.call_api(
            '/testcasetree/leaf/rename', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def suggest4(self, project_id : StrictInt, query : Optional[StrictStr] = None, tree_id : Optional[StrictInt] = None, path : Optional[conlist(StrictInt)] = None, id : Optional[conlist(StrictInt)] = None, ignore_id : Optional[conlist(StrictInt)] = None, page : Annotated[Optional[conint(strict=True, ge=0)], Field(description="Zero-based page index (0..N)")] = None, size : Annotated[Optional[conint(strict=True, ge=1)], Field(description="The size of the page to be returned")] = None, sort : Annotated[Optional[conlist(StrictStr)], Field(description="Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.")] = None, **kwargs) -> PageIdAndNameOnlyDto:  # noqa: E501
        """Tree groups suggest  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.suggest4(project_id, query, tree_id, path, id, ignore_id, page, size, sort, async_req=True)
        >>> result = thread.get()

        :param project_id: (required)
        :type project_id: int
        :param query:
        :type query: str
        :param tree_id:
        :type tree_id: int
        :param path:
        :type path: List[int]
        :param id:
        :type id: List[int]
        :param ignore_id:
        :type ignore_id: List[int]
        :param page: Zero-based page index (0..N)
        :type page: int
        :param size: The size of the page to be returned
        :type size: int
        :param sort: Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
        :type sort: List[str]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: PageIdAndNameOnlyDto
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the suggest4_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.suggest4_with_http_info(project_id, query, tree_id, path, id, ignore_id, page, size, sort, **kwargs)  # noqa: E501

    @validate_arguments
    def suggest4_with_http_info(self, project_id : StrictInt, query : Optional[StrictStr] = None, tree_id : Optional[StrictInt] = None, path : Optional[conlist(StrictInt)] = None, id : Optional[conlist(StrictInt)] = None, ignore_id : Optional[conlist(StrictInt)] = None, page : Annotated[Optional[conint(strict=True, ge=0)], Field(description="Zero-based page index (0..N)")] = None, size : Annotated[Optional[conint(strict=True, ge=1)], Field(description="The size of the page to be returned")] = None, sort : Annotated[Optional[conlist(StrictStr)], Field(description="Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.")] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """Tree groups suggest  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.suggest4_with_http_info(project_id, query, tree_id, path, id, ignore_id, page, size, sort, async_req=True)
        >>> result = thread.get()

        :param project_id: (required)
        :type project_id: int
        :param query:
        :type query: str
        :param tree_id:
        :type tree_id: int
        :param path:
        :type path: List[int]
        :param id:
        :type id: List[int]
        :param ignore_id:
        :type ignore_id: List[int]
        :param page: Zero-based page index (0..N)
        :type page: int
        :param size: The size of the page to be returned
        :type size: int
        :param sort: Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
        :type sort: List[str]
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(PageIdAndNameOnlyDto, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'project_id',
            'query',
            'tree_id',
            'path',
            'id',
            'ignore_id',
            'page',
            'size',
            'sort'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method suggest4" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('query') is not None:  # noqa: E501
            _query_params.append(('query', _params['query']))

        if _params.get('project_id') is not None:  # noqa: E501
            _query_params.append(('projectId', _params['project_id']))

        if _params.get('tree_id') is not None:  # noqa: E501
            _query_params.append(('treeId', _params['tree_id']))

        if _params.get('path') is not None:  # noqa: E501
            _query_params.append(('path', _params['path']))
            _collection_formats['path'] = 'multi'

        if _params.get('id') is not None:  # noqa: E501
            _query_params.append(('id', _params['id']))
            _collection_formats['id'] = 'multi'

        if _params.get('ignore_id') is not None:  # noqa: E501
            _query_params.append(('ignoreId', _params['ignore_id']))
            _collection_formats['ignoreId'] = 'multi'

        if _params.get('page') is not None:  # noqa: E501
            _query_params.append(('page', _params['page']))

        if _params.get('size') is not None:  # noqa: E501
            _query_params.append(('size', _params['size']))

        if _params.get('sort') is not None:  # noqa: E501
            _query_params.append(('sort', _params['sort']))
            _collection_formats['sort'] = 'multi'

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # authentication setting
        _auth_settings = []  # noqa: E501

        _response_types_map = {
            '200': "PageIdAndNameOnlyDto",
        }

        return self.api_client.call_api(
            '/testcasetree/suggest', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
