apiVersion: v1
data:
  swapper.yaml: "alive_check:\n  background_check_interval: 1m\n  count_threads: 1\n\
    \  enabled_background_check: false\n  fail_interval: 10s\napp:\n  await_ready_timeout:\
    \ 1m\n  await_stop_timeout: 5s\nctlr:\n  dial_timeout: 2s\n  map: swapper\n  server:\
    \ ctlr.service.onpremise.consul:2410\n  verbose: false\nhost: onpremise\nhttp:\n\
    \  listen: 0.0.0.0:8080\n  shutdown_timeout: 3s\ninstance_name: swapper-1\nipros:\n\
    \  boss: boss\n  boss_timeout: 3s\n  map_timeout: 3s\nlog:\n  async: true\n  level:\
    \ info\nprobes:\n  address: 0.0.0.0:5550\n  enabled: true\nsaws:\n  api_version:\
    \ v130\n  host: https://u.vkt-zakhtarenko.swa.vkwm.ru\n  timeout: 3s\nservice_name:\
    \ swapper\nstroma:\n  api_version: v1\n  host: https://u.vkt-zakhtarenko.swa.vkwm.ru\n\
    \  timeout: 3s\nswap:\n  miniapp_access_ttl: 300\n  miniapp_api_token: 5a1083a11c492a72c13837de59015409a32c3e77f5726207b8bc6e03385a6c9b\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","data":{"swapper.yaml":"alive_check:\n  background_check_interval:
      1m\n  count_threads: 1\n  enabled_background_check: false\n  fail_interval:
      10s\napp:\n  await_ready_timeout: 1m\n  await_stop_timeout: 5s\nctlr:\n  dial_timeout:
      2s\n  map: swapper\n  server: ctlr.service.onpremise.consul:2410\n  verbose:
      false\nhost: onpremise\nhttp:\n  listen: 0.0.0.0:8080\n  shutdown_timeout: 3s\ninstance_name:
      swapper-1\nipros:\n  boss: boss\n  boss_timeout: 3s\n  map_timeout: 3s\nlog:\n  async:
      true\n  level: info\nprobes:\n  address: 0.0.0.0:5550\n  enabled: true\nsaws:\n  api_version:
      v130\n  host: https://u.vkt-zakhtarenko.swa.vkwm.ru\n  timeout: 3s\nservice_name:
      swapper\nstroma:\n  api_version: v1\n  host: https://u.vkt-zakhtarenko.swa.vkwm.ru\n  timeout:
      3s\nswap:\n  miniapp_access_ttl: 300\n  miniapp_api_token: 5a1083a11c492a72c13837de59015409a32c3e77f5726207b8bc6e03385a6c9b\n"},"kind":"ConfigMap","metadata":{"annotations":{"meta.helm.sh/release-name":"swapper","meta.helm.sh/release-namespace":"vkteams"},"creationTimestamp":"2026-01-15T10:01:23Z","labels":{"app":"swapper","app.kubernetes.io/managed-by":"Helm","chart":"vkunited-6.0.0","heritage":"Helm"},"name":"swapper-config","namespace":"vkteams","resourceVersion":"2601741","uid":"c62fb608-b4de-4736-9a7d-e5250bcc02df"}}

      '
    meta.helm.sh/release-name: swapper
    meta.helm.sh/release-namespace: vkteams
  creationTimestamp: '2026-01-15T10:01:23Z'
  labels:
    app: swapper
    app.kubernetes.io/managed-by: Helm
    chart: vkunited-6.0.0
    heritage: Helm
  name: swapper-config
  namespace: vkteams
  resourceVersion: '2602480'
  uid: c62fb608-b4de-4736-9a7d-e5250bcc02df
